version: '3.4'

services:
  version-test:
    env_file: .env
    image: version-test
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
